### ISSUE TITLE
Program won't launch

### ISSUE THREAD

**Issue by ML4W** [UltimateFishbot/UltimateFishbot#83]
Since the Win10 update this morning 9/29/16,fishbot won't launch under any compatibility settings, with or without administrative permissions.

**Comment by pytancn** [comment]
same problem here! 
changed also compability setting, admin permissions
i downloaded and tried to install all ,NET frameworks (3.5 , 4 , 4.6) but all of them are "part of my system"

**Comment by Drakier** [comment]
I am having the exact same issue.  I launch the program the hour glass pops up and then nothing.

**Comment by ezspot** [comment]
This bot works with Legion?

**Comment by Drakier** [comment]
Yeah works great.

**Comment by ezspot** [comment]
Safe? Been banned?

**Comment by Drakier** [comment]
Probably 200 hours fishing have not been banned.  Legion has built in not
safeguards where you catch things that attack you and you catch boots that
full your inventory.

**Comment by ezspot** [comment]
Not working for me, it won't loot. Got a tip?

**Comment by Drakier** [comment]
Make sure auto loot is enabled in you wow settings

**Comment by Fartonice-Dev** [comment]
ok im geting this 
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreAudioApi.Interfaces.IMMDevice.Activate(Guid& iid, CLSCTX dwClsCtx, IntPtr pActivationParams, Object& ppInterface)
   at CoreAudioApi.MMDevice.GetAudioMeterInformation()
   at CoreAudioApi.MMDevice.get_AudioMeterInformation()
   at UltimateFishBot.Classes.BodyParts.Ears.ListenTimerTick(Object myObject, EventArgs myEventArgs) in c:\projects\ultimatefishbot\UltimateFishBot\Classes\BodyParts\Ears.cs:line 40
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
UltimateFishBot
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Anonymous/Documents/fishing%20bot/UltimateFishBot.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
CoreAudioApi
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Anonymous/Documents/fishing%20bot/CoreAudioApi.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by wanttofish** [comment]
So did anyone have a solution to this?

**Comment by Fartonice-Dev** [comment]
I uninstalled and reinstalled it and it worked

**Comment by NaNraptor** [comment]
Use latest version :)
