### ISSUE TITLE
Getting Microsoft error only on anti AFK jump option

### ISSUE THREAD

**Issue by kaseyd24** [UltimateFishbot/UltimateFishbot#99]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at UltimateFishBot.Classes.BodyParts.Legs.DoMovement(T2S t2s)
   at UltimateFishBot.Classes.Manager.HandleNeededAction(NeededAction action)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by NaNraptor** [comment]
Try newest version, I have not encountered that error before - even in older versions, let me know if it works for you
